In [1]:

import numpy as np
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import tensorflow as tf
from keras.layers import Conv2D


C:\Users\Franc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.18) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
C:\Users\Franc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [5]:
input_matrix = np.array([[1, 2, 3, 4, 5],
                        [6, 7, 8, 9, 10],
                        [11, 12, 13, 14, 15],
                        [16, 17, 18, 19, 20],
                        [21, 22, 23, 24, 25]])

input_test1 = np.array([[1, 1, 1, 1, 1],
                        [1, 1, 1, 1, 1],
                        [1, 1, 1, 1, 1],
                        [1, 1, 1, 1, 1],
                        [1, 1, 1, 1, 1]])

# Définir le filtre (2x2)
filter_matrix = np.array([[2, 0],
                         [1, 2]])

filter_test1 = np.array([[0, 1, 2],
                         [1, 0, 3],
                         [2, 3, 0]])

# Ajouter une dimension pour indiquer le nombre de canaux (1 dans ce cas car c'est une image en niveaux de gris)
input_matrix = input_matrix.reshape((1, 5, 5, 1))
filter_matrix = filter_matrix.reshape((2, 2, 1, 1))
input_matrix_test1 = input_test1.reshape((1, 5, 5, 1))
filter_matrix_test1 = filter_test1.reshape((3, 3, 1, 1))
# Appliquer la convolution
result = tf.nn.conv2d(input_matrix_test1, filter_matrix_test1, strides=[1, 1, 1, 1], padding='VALID')

# Afficher le résultat
print(result.numpy().reshape(3, 3))

[[12 12 12]
 [12 12 12]
 [12 12 12]]


In [ ]:
import tensorflow as tf
from keras.layers import Conv2D
from keras.models import Sequential

# Créer un modèle séquentiel
model = Sequential()

# Ajouter une couche Conv2D avec 32 filtres, une taille de noyau de (3,3), une activation ReLU et une entrée 64x64 avec 3 canaux (RGB)
model.add(Conv2D(1, kernel_size=(2, 2), activation=None, input_shape=(5, 5, 1)))


In [ ]:
print(filter_matrix.shape)
print(input_matrix.shape)

(2, 2, 1, 1)
(1, 5, 5, 1)


In [ ]:
filter1 = model.get_weights()[0].reshape(2,2,1,1)
print(filter1.shape)

(2, 2, 1, 1)


In [ ]:
print(model.predict(input_matrix, verbose=0).reshape(4,4))

[[ 4.857754   5.443286   6.0288177  6.6143494]
 [ 7.785413   8.370944   8.956476   9.542008 ]
 [10.713072  11.298603  11.884136  12.4696665]
 [13.640731  14.226263  14.811794  15.3973255]]


In [ ]:
input_tensor = tf.constant(input_matrix, dtype=tf.float64)
filter1 = tf.constant(filter1, dtype=tf.float64)
result = tf.nn.conv2d(input_matrix, filter1, strides=[1, 1, 1, 1], padding='VALID')
print(result.numpy().reshape(4,4))

[[ 4.85775417  5.44328594  6.02881771  6.61434948]
 [ 7.78541303  8.3709448   8.95647657  9.54200834]
 [10.71307188 11.29860365 11.88413543 12.4696672 ]
 [13.64073074 14.22626251 14.81179428 15.39732605]]
