In [1]:

import numpy as np
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import tensorflow as tf
from keras.layers import Conv2D
from rich import print


C:\Users\Franc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [7]:
input_matrix = np.array([[1, 2, 3, 4, 5],
                        [6, 7, 8, 9, 10],
                        [11, 12, 13, 14, 15],
                        [16, 17, 18, 19, 20],
                        [21, 22, 23, 24, 25]])

input_test1 = np.array([[1, 1, 1, 1, 1],
                        [1, 1, 1, 1, 1],
                        [1, 1, 1, 1, 1],
                        [1, 1, 1, 1, 1],
                        [1, 1, 1, 1, 1]])

input_test2 = np.array([[1, 2, 3, 4, 5],
                        [2, 3, 4, 5, 6],
                        [3, 4, 5, 6, 7],
                        [4, 5, 6, 7, 8],
                        [5, 6, 7, 8, 9]])

# Définir le filtre (2x2)
filter_matrix = np.array([[2, 0],
                         [1, 2]])

filter_test1 = np.array([[0, 1, 2],
                         [1, 0, 3],
                         [2, 3, 0]])

filter_test2 = np.array([[0, 1, 2],
                         [1, 2, 3],
                         [2, 3, 4]])

filter_test3 = np.array([[0, 1, 2],
                        [3, 4, 5],
                        [6, 7, 8]])
# Ajouter une dimension pour indiquer le nombre de canaux (1 dans ce cas car c'est une image en niveaux de gris)
input_matrix = input_matrix.reshape((1, 5, 5, 1))
filter_matrix = filter_matrix.reshape((2, 2, 1, 1))
input_matrix_test1 = input_test1.reshape((1, 5, 5, 1))
filter_matrix_test1 = filter_test1.reshape((3, 3, 1, 1))
input_matrix_test2 = input_test2.reshape((1, 5, 5, 1))
filter_matrix_test2 = filter_test2.reshape((3, 3, 1, 1))
filter_matrix_test3 = filter_test3.reshape((3, 3, 1, 1))
# Appliquer la convolution
result = tf.nn.conv2d(input_matrix, filter_matrix_test3, strides=[1, 1, 1, 1], padding='VALID')

# Afficher le résultat
print(input_matrix.reshape(5, 5))
print(filter_matrix_test3.reshape(3, 3))
print(result.numpy().reshape(3, 3))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[348 384 420]
 [528 564 600]
 [708 744 780]]

In [4]:
import tensorflow as tf
from keras.layers import Conv2D
from keras.models import Sequential

# Créer un modèle séquentiel
model = Sequential()

# Ajouter une couche Conv2D avec 32 filtres, une taille de noyau de (3,3), une activation ReLU et une entrée 64x64 avec 3 canaux (RGB)
model.add(Conv2D(1, kernel_size=(2, 2), activation=None, input_shape=(5, 5, 1)))


In [6]:
def array2string(array: np.array) -> list[str, str]:
    dim = array.shape
    string_arr = "["
    for i in range(dim[0]):
        for j in range(dim[1]):
            string_arr += str(array[i][j])
            string_arr += ','
    string_arr = string_arr[:-1] + ']'
    
    return str(dim[0])+","+str(dim[1]) , string_arr

def py2txt(file: str, string, name="") -> None:
    with open(file, "a") as f:
        if type(string) == str:
            f.write(string)
        else:
            for word in string:
                f.write(word)
                f.write("-")
        f.write(name)
        f.write("-\n")
input1 = np.array([ [1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20],
                    [21, 22, 23, 24, 25]])

# input2 = np.round( np.random.random((5,5))*10, 2)

# input3 = np.round( np.random.random((10,10))*10, 3)

# input4 = np.round( np.random.random((32,32))*10, 2)

filter1 = np.array([[2, 0],
                    [1, 2]])

filter2 = np.array([[0, 1, 2],
                    [1, 0, 3],
                    [2, 3, 0]])

filter3 = np.array([[0, 1, 2],
                    [3, 4, 5],
                    [6, 7, 8]])

# filter3 = np.round( np.random.random((3,3)), 2)

# filter4 = np.round( np.random.random((5,5)), 2)

array2string(input1)

('5,5', '[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]')

In [14]:
py2txt("test_convolution.txt", array2string(input1),"input1")
py2txt("test_convolution.txt", array2string(input2),"input2")
py2txt("test_convolution.txt", array2string(input3),"input3")
py2txt("test_convolution.txt", array2string(input4),"input4")

py2txt("test_convolution.txt", array2string(filter1),"filter1")
py2txt("test_convolution.txt", array2string(filter2),"filter2")
py2txt("test_convolution.txt", array2string(filter3),"filter3")
py2txt("test_convolution.txt", array2string(filter4),"filter4")


In [15]:
32*32*5


5120