In [2]:

import numpy as np
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import tensorflow as tf
from keras.layers import Conv2D


C:\Users\Franc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.18) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
C:\Users\Franc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [3]:
input_matrix = np.array([[1, 2, 3, 4, 5],
                        [6, 7, 8, 9, 10],
                        [11, 12, 13, 14, 15],
                        [16, 17, 18, 19, 20],
                        [21, 22, 23, 24, 25]])

input_test1 = np.array([[1, 1, 1, 1, 1],
                        [1, 1, 1, 1, 1],
                        [1, 1, 1, 1, 1],
                        [1, 1, 1, 1, 1],
                        [1, 1, 1, 1, 1]])

# Définir le filtre (2x2)
filter_matrix = np.array([[2, 0],
                         [1, 2]])

filter_test1 = np.array([[0, 1, 2],
                         [1, 0, 3],
                         [2, 3, 0]])

# Ajouter une dimension pour indiquer le nombre de canaux (1 dans ce cas car c'est une image en niveaux de gris)
input_matrix = input_matrix.reshape((1, 5, 5, 1))
filter_matrix = filter_matrix.reshape((2, 2, 1, 1))
input_matrix_test1 = input_test1.reshape((1, 5, 5, 1))
filter_matrix_test1 = filter_test1.reshape((3, 3, 1, 1))
# Appliquer la convolution
result = tf.nn.conv2d(input_matrix_test1, filter_matrix_test1, strides=[1, 1, 1, 1], padding='VALID')

# Afficher le résultat
print(result.numpy().reshape(3, 3))

[[12 12 12]
 [12 12 12]
 [12 12 12]]


In [4]:
import tensorflow as tf
from keras.layers import Conv2D
from keras.models import Sequential

# Créer un modèle séquentiel
model = Sequential()

# Ajouter une couche Conv2D avec 32 filtres, une taille de noyau de (3,3), une activation ReLU et une entrée 64x64 avec 3 canaux (RGB)
model.add(Conv2D(1, kernel_size=(2, 2), activation=None, input_shape=(5, 5, 1)))


In [5]:
print(filter_matrix.shape)
print(input_matrix.shape)

(2, 2, 1, 1)
(1, 5, 5, 1)


In [6]:
filter1 = model.get_weights()[0].reshape(2,2,1,1)
print(filter1.shape)

(2, 2, 1, 1)


In [7]:
print(model.predict(input_matrix, verbose=0).reshape(4,4))

[[ 7.044731  8.199986  9.355242 10.510496]
 [12.821007 13.976261 15.131516 16.286772]
 [18.597282 19.752537 20.907791 22.063047]
 [24.373556 25.52881  26.684067 27.839321]]


In [8]:
input_tensor = tf.constant(input_matrix, dtype=tf.float64)
filter1 = tf.constant(filter1, dtype=tf.float64)
result = tf.nn.conv2d(input_matrix, filter1, strides=[1, 1, 1, 1], padding='VALID')
print(result.numpy().reshape(4,4))

[[ 7.04473132  8.19998634  9.35524136 10.51049638]
 [12.82100642 13.97626144 15.13151646 16.28677148]
 [18.59728152 19.75253654 20.90779155 22.06304657]
 [24.37355661 25.52881163 26.68406665 27.83932167]]


In [13]:
def array2string(array: np.array) -> list[str, str]:
    dim = array.shape
    string_arr = "["
    for i in range(dim[0]):
        for j in range(dim[1]):
            string_arr += str(array[i][j])
            string_arr += ','
    string_arr = string_arr[:-1] + ']'
    
    return str(dim[0])+","+str(dim[1]) , string_arr

def py2txt(file: str, string, name="") -> None:
    with open(file, "a") as f:
        if type(string) == str:
            f.write(string)
        else:
            for word in string:
                f.write(word)
                f.write("-")
        f.write(name)
        f.write("-\n")
input1 = np.array([ [1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20],
                    [21, 22, 23, 24, 25]])

input2 = np.round( np.random.random((5,5))*10, 2)

input3 = np.round( np.random.random((10,10))*10, 3)

input4 = np.round( np.random.random((32,32))*10, 2)

filter1 = np.array([[2, 0],
                    [1, 2]])

filter2 = np.array([[0, 1, 2],
                    [1, 0, 3],
                    [2, 3, 0]])

filter3 = np.round( np.random.random((3,3)), 2)

filter4 = np.round( np.random.random((5,5)), 2)

array2string(input1)

('5,5', '[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]')

In [14]:
py2txt("test_convolution.txt", array2string(input1),"input1")
py2txt("test_convolution.txt", array2string(input2),"input2")
py2txt("test_convolution.txt", array2string(input3),"input3")
py2txt("test_convolution.txt", array2string(input4),"input4")

py2txt("test_convolution.txt", array2string(filter1),"filter1")
py2txt("test_convolution.txt", array2string(filter2),"filter2")
py2txt("test_convolution.txt", array2string(filter3),"filter3")
py2txt("test_convolution.txt", array2string(filter4),"filter4")


In [15]:
32*32*5


5120